name: OCR and Crop Images

on:
  push:
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  ocr_and_crop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install easyocr pillow

    - name: Run OCR and crop script
      run: |
        python main.py

    - name: commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        # Check if there are any changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "update images"
          git pull origin ${{ github.ref }} --rebase
          git push origin ${{ github.ref }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
